language: python
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
jobs:
  include:
    - stage: code-style
      script: flake8 ./
    - stage: static-analyze
      script: find . -type f -name "*.py" | xargs pylint 
